CREATE SCHEMA keep DEFAULT CHARACTER SET utf8;

CREATE TABLE keep.nota (
  id INT NOT NULL AUTO_INCREMENT,
  titulo VARCHAR(256) NULL,
  conteudo VARCHAR(4096) NULL,
  situacao INT(1) NULL,
  PRIMARY KEY (id)
) ENGINE = NDBCLUSTER;

CREATE TABLE keep.usuario (
  id INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(256) NULL,
  usuario VARCHAR(4096) NULL,
  senha VARCHAR(128) NULL,
  PRIMARY KEY (id)
) ENGINE = NDBCLUSTER;
